version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    networks:
      - proxy-minio
    ports:
      - 80:8080
    volumes:
      - ./nginx/:/etc/nginx/

  minio:
    image: minio/minio
    container_name: minio
    networks:
      - proxy-minio
    ports:
      - 9001:9001
    environment:
      - "MINIO_ROOT_USER=user"
      - "MINIO_ROOT_PASSWORD=password"
    volumes:
      - ./testdata:/data
    command: server /data --console-address ":9001"

networks:
  proxy-minio:
    name: proxy-minio
